package com.ondar.bagel.domain;

import static com.ondar.bagel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAllPropertiesEquals(OrderLine expected, OrderLine actual) {
        assertOrderLineAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAllUpdatablePropertiesEquals(OrderLine expected, OrderLine actual) {
        assertOrderLineUpdatableFieldsEquals(expected, actual);
        assertOrderLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineAutoGeneratedPropertiesEquals(OrderLine expected, OrderLine actual) {
        assertThat(expected)
            .as("Verify OrderLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineUpdatableFieldsEquals(OrderLine expected, OrderLine actual) {
        assertThat(expected)
            .as("Verify OrderLine relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLineUpdatableRelationshipsEquals(OrderLine expected, OrderLine actual) {
        assertThat(expected)
            .as("Verify OrderLine relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
